/// Maps an ISO 639-1 language code -- what TMDB's `original_language`
/// field returns (e.g. "en", "ko", "fr") -- to a human-readable display
/// name, so the Statistics screen can group by language consistently
/// whether the underlying match came from TMDB (a code) or OMDb (already
/// a name, handled separately in `providers.dart`).
///
/// Falls back to the upper-cased code itself for anything not in this
/// table, so an unmapped language still shows as something meaningful
/// rather than disappearing.
String languageNameForCode(String? code) {
  final normalized = code?.trim().toLowerCase();
  if (normalized == null || normalized.isEmpty) return '';
  return _iso639NameByCode[normalized] ?? normalized.toUpperCase();
}

const Map<String, String> _iso639NameByCode = {
  'en': 'English',
  'fr': 'French',
  'es': 'Spanish',
  'de': 'German',
  'it': 'Italian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'zh': 'Chinese',
  'cn': 'Chinese',
  'hi': 'Hindi',
  'pt': 'Portuguese',
  'ru': 'Russian',
  'ar': 'Arabic',
  'tr': 'Turkish',
  'fa': 'Persian',
  'sv': 'Swedish',
  'da': 'Danish',
  'no': 'Norwegian',
  'nl': 'Dutch',
  'pl': 'Polish',
  'th': 'Thai',
  'vi': 'Vietnamese',
  'id': 'Indonesian',
  'he': 'Hebrew',
  'el': 'Greek',
  'uk': 'Ukrainian',
  'fi': 'Finnish',
  'cs': 'Czech',
  'hu': 'Hungarian',
  'ro': 'Romanian',
  'ms': 'Malay',
  'bn': 'Bengali',
  'ta': 'Tamil',
  'te': 'Telugu',
  'ur': 'Urdu',
  'sw': 'Swahili',
  'sr': 'Serbian',
  'hr': 'Croatian',
  'bg': 'Bulgarian',
  'sk': 'Slovak',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'et': 'Estonian',
  'is': 'Icelandic',
  'ga': 'Irish',
  'cy': 'Welsh',
  'ca': 'Catalan',
  'eu': 'Basque',
  'gl': 'Galician',
  'af': 'Afrikaans',
  'sq': 'Albanian',
  'hy': 'Armenian',
  'az': 'Azerbaijani',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'mn': 'Mongolian',
  'ne': 'Nepali',
  'si': 'Sinhala',
  'km': 'Khmer',
  'lo': 'Lao',
  'my': 'Burmese',
  'am': 'Amharic',
  'zu': 'Zulu',
  'xh': 'Xhosa',
  'yo': 'Yoruba',
  'ig': 'Igbo',
  'ha': 'Hausa',
  'mk': 'Macedonian',
  'sl': 'Slovenian',
  'bs': 'Bosnian',
  'mr': 'Marathi',
  'gu': 'Gujarati',
  'kn': 'Kannada',
  'ml': 'Malayalam',
  'pa': 'Punjabi',
  'ku': 'Kurdish',
  'ps': 'Pashto',
  'tl': 'Tagalog',
  'xx': 'No Language',
};
